scrapers:
  usgov:
    treasury_info:
      params: 
        year:
          - 2018
          - 2019
          - 2020
          - 2021
          - 2022
          - 2023
        type:
          - "YIELD_CURVE"
          - "BILL_RATES"
          - "LONG_TERM_RATE"
          - "REAL_YIELD_CURVE"
          - "REAL_LONG_TERM"
      schedule:
        cron: "01 00 * * *"
        timezone: America/New_York