version: '3.8'
services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:12.3
    env_file: env/docker.env
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql