version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    env_file: ./zookeeper/env/docker.env
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - ${ION_MAPPED_ZK_PORT:-2181}:2181
  broker:
    image: confluentinc/cp-kafka:5.4.0
    env_file: ./broker/env/docker.env
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - ${ION_MAPPED_KAFKA_BROKER_PORT:-9092}:9092