version: "3"

services:

  frontend:
    build: 
      context: ../
      dockerfile: docker/frontend/Dockerfile 
    env_file: frontend/docker.env
    environment: 
      - REACT_APP_DATA_INGESTION_BASE_URL="https://api.finflow.cloud/"
      - REACT_APP_ION_BACKEND_BASE_URL="https://ionapi.finflow.cloud/"
    depends_on:
      - data-backend
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - ../frontend:/app/frontend
      - /etc/letsencrypt:/etc/letsencrypt
    stdin_open: true
    tty: true
    networks:
      - ion-network

  data-backend:
    build: 
      context: ../
      dockerfile: docker/data-backend/Dockerfile 
    env_file: data-backend/docker.env
    ports:
      - "1236:1236"
    depends_on:
      - database
    links:
      - database:database
    stdin_open: true
    tty: true
    networks:
      - ion-network

  ion-backend:
    build: 
      context: ../
      dockerfile: docker/ion-backend/Dockerfile 
    env_file: ion-backend/docker.env
    environment: 
      - POSTGRES_URI="postgresql://postgres:guest@localhost:5432/postgres"
    ports:
      - "1237:1237"
    depends_on:
      - database
    links:
      - database:database
    stdin_open: true
    tty: true
    networks:
      - ion-network

  database:
    container_name: postgres-database
    image: postgres:12.3
    environment: 
      - POSTGRES_USER=guest
      - POSTGRES_PASSWORD=guest
    hostname: postgres
    ports:
      - 5432:5432
    networks:
      - ion-network

networks:
  ion-network:
    driver: bridge
