version: "3"
networks:
  prefect:
    name: prefect
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    env_file: ./zookeeper/env/docker.env
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - ${ION_MAPPED_ZK_PORT:-2181}:2181

  broker:
    image: confluentinc/cp-kafka:5.4.0
    env_file: ./broker/env/docker.env
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - ${ION_MAPPED_KAFKA_BROKER_PORT:-9092}:9092

  schema-registry:
    image: confluentinc/cp-schema-registry:5.4.0
    env_file: ./schema-registry/env/docker.env
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - zookeeper
      - broker
    ports:
      - ${ION_MAPPED_SCHEMA_REGISTRY_PORT:-8081}:8081

  postgres:
    image: postgres:12.3
    env_file: ./postgres/env/docker.env
    hostname: postgres
    container_name: postgres
    ports:
      - "5432:5432"

  prefect-server:
    image: prefecthq/prefect:sha-33f7de5-python3.9
    command:
      - prefect
      - orion
      - start
    depends_on:
      - postgres
    ports:
      - 4200:4200
    networks:
      - prefect
    