version: "3"

services:

  frontend:
    build: 
      context: ../
      dockerfile: docker/frontend/Dockerfile 
      args:
        - REACT_APP_DATA_INGESTION_BASE_URL=https://api.ykanalytics.com/api # Point to the backend
    env_file: docker/frontend/docker.env
    depends_on:
      - data-ingestion
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - /etc/letsencrypt:/etc/letsencrypt
    stdin_open: true
    tty: true
    networks:
      - djangonetwork

  data-ingestion:
    build: 
      context: ../
      dockerfile: docker/data-ingestion/Dockerfile 
    ports:
      - "1236:1236"
    depends_on:
      - database
    links:
      - database:database
    stdin_open: true
    tty: true
    networks:
      - djangonetwork

  postgres-database:
    container_name: postgres-database
    image: postgres:12.3
    env_file: ../postgres/docker.env
    hostname: postgres
    ports:
      - 5432:5432
