version: "3"

services:

  frontend:
    build: 
      context: ../
      dockerfile: docker/frontend/Dockerfile 
    env_file: frontend/docker.env
    depends_on:
      - data-backend
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - /etc/letsencrypt:/etc/letsencrypt
    stdin_open: true
    tty: true

  data-backend:
    build: 
      context: ../
      dockerfile: docker/data-backend/Dockerfile 
    env_file: data-backend/docker.env
    ports:
      - "1236:1236"
    depends_on:
      - database
    links:
      - database:database
    stdin_open: true
    tty: true

  database:
    container_name: postgres-database
    image: postgres:12.3
    env_file: postgres/docker.env
    hostname: postgres
    ports:
      - 5432:5432
