version: "3"

services:
  prefect-server:
    container_name: prefect-server
    build:
      context: ../
      dockerfile: docker/prefect/Dockerfile
    command:
      - prefect
      - orion
      - start
    ports:
      - 4200:4200
    depends_on:
      postgres:
        condition: service_started
    environment:
      PREFECT_ORION_ANALYTICS_ENABLED: "false"
      PREFECT_LOGGING_SERVER_LEVEL: WARNING
    networks:
      - prefect
  prefect-agent:
    container_name: prefect-agent
    image: prefecthq/prefect:2.7-python3.9
    command:
      - prefect
      - agent
      - start
      - -q
      - treasury
      - common
    depends_on:
      prefect-server:
        condition: service_started
    environment:
      PREFECT_LOGGING_LEVEL: DEBUG
      DOCKER_HOST: unix://var/run/docker.sock
      PREFECT_API_URL: http://prefect-server:4200/api
    networks:
      - prefect
networks:
  prefect:
    driver: bridge