version: "3"

services:
  postgres-database:
    container_name: postgres-database
    image: postgres:12.3
    env_file: ./postgres/env/docker.env
    hostname: postgres
    ports:
      - "5432:5432"